[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepositoryRoot = Split-Path -Parent $PSScriptRoot
$SourceRoot = Join-Path $RepositoryRoot "native\src"
$ScintillaInterface = Join-Path $SourceRoot "scintilla\include\Scintilla.iface"
$LexillaInterface = Join-Path $SourceRoot "lexilla\include\LexicalStyles.iface"
$OutputPath = Join-Path $RepositoryRoot "src\editor\scintilla_constants.rs"

& (Join-Path $PSScriptRoot "fetch-native.ps1") -VerifyOnly
if (-not $?) {
    throw "Native source verification failed"
}

$RequiredNames = @(
    "SCI_GETDIRECTFUNCTION", "SCI_GETDIRECTPOINTER", "SCI_SETCODEPAGE", "SCI_SETTEXT",
    "SCI_GETTEXT", "SCI_GETTEXTLENGTH", "SCI_GETLENGTH", "SCI_SETUNDOCOLLECTION",
    "SCI_EMPTYUNDOBUFFER", "SCI_SETSAVEPOINT", "SCI_BEGINUNDOACTION", "SCI_ENDUNDOACTION",
    "SCI_CREATEDOCUMENT", "SCI_ADDREFDOCUMENT", "SCI_RELEASEDOCUMENT", "SCI_GETDOCPOINTER",
    "SCI_SETDOCPOINTER", "SCI_UNDO", "SCI_REDO", "SCI_CANUNDO", "SCI_CANREDO", "SCI_CUT",
    "SCI_COPY", "SCI_PASTE", "SCI_GETSELECTIONSTART", "SCI_GETSELECTIONEND", "SCI_SETSEL",
    "SCI_LINEFROMPOSITION", "SCI_GETCOLUMN", "SCI_POSITIONFROMLINE", "SCI_GETLINEENDPOSITION",
    "SCI_SETTARGETRANGE", "SCI_SEARCHINTARGET", "SCI_REPLACETARGET", "SCI_SETSEARCHFLAGS",
    "SCI_SETILEXER", "SCI_STYLESETFORE", "SCI_STYLESETBACK", "SCI_STYLESETFONT", "SCI_STYLESETBOLD",
    "SCI_STYLESETSIZEFRACTIONAL", "SCI_STYLECLEARALL", "SCI_SETMARGINTYPEN", "SCI_SETMARGINWIDTHN",
    "SCI_SETWRAPMODE", "SCI_SETTABWIDTH", "SCI_GETMODIFY", "SC_CP_UTF8", "SCN_SAVEPOINTREACHED",
    "SCN_SAVEPOINTLEFT", "SCN_MODIFIED", "SC_MOD_INSERTTEXT", "SC_MOD_DELETETEXT", "SC_WRAP_NONE",
    "SC_WRAP_WORD", "SCE_JSON_DEFAULT", "SCE_JSON_NUMBER", "SCE_JSON_STRING", "SCE_JSON_STRINGEOL",
    "SCE_JSON_PROPERTYNAME", "SCE_JSON_ESCAPESEQUENCE", "SCE_JSON_LINECOMMENT", "SCE_JSON_BLOCKCOMMENT",
    "SCE_JSON_OPERATOR", "SCE_JSON_URI", "SCE_JSON_COMPACTIRI", "SCE_JSON_KEYWORD", "SCE_JSON_LDKEYWORD",
    "SCE_JSON_ERROR", "SCE_MARKDOWN_DEFAULT", "SCE_MARKDOWN_LINE_BEGIN", "SCE_MARKDOWN_STRONG1",
    "SCE_MARKDOWN_STRONG2", "SCE_MARKDOWN_EM1", "SCE_MARKDOWN_EM2", "SCE_MARKDOWN_HEADER1",
    "SCE_MARKDOWN_HEADER2", "SCE_MARKDOWN_HEADER3", "SCE_MARKDOWN_HEADER4", "SCE_MARKDOWN_HEADER5",
    "SCE_MARKDOWN_HEADER6", "SCE_MARKDOWN_PRECHAR", "SCE_MARKDOWN_ULIST_ITEM", "SCE_MARKDOWN_OLIST_ITEM",
    "SCE_MARKDOWN_BLOCKQUOTE", "SCE_MARKDOWN_STRIKEOUT", "SCE_MARKDOWN_HRULE", "SCE_MARKDOWN_LINK",
    "SCE_MARKDOWN_CODE", "SCE_MARKDOWN_CODE2", "SCE_MARKDOWN_CODEBK",
    "SCI_GETSELTEXT", "SCFIND_NONE", "SCFIND_WHOLEWORD", "SCFIND_MATCHCASE", "SCI_SCROLLCARET",
    "STYLE_DEFAULT", "SCI_GETTABWIDTH", "SCI_SETCARETFORE", "SCI_SETSCROLLWIDTH",
    "SCI_SETSCROLLWIDTHTRACKING", "SCI_SETELEMENTCOLOUR", "SCI_RESETELEMENTCOLOUR",
    "SC_ELEMENT_SELECTION_BACK", "SC_ELEMENT_SELECTION_TEXT",
    "SC_ELEMENT_SELECTION_INACTIVE_BACK", "SC_ELEMENT_SELECTION_INACTIVE_TEXT",
    "SC_ELEMENT_CARET_LINE_BACK", "SCI_GETFIRSTVISIBLELINE",
    "SCI_SETFIRSTVISIBLELINE", "SCI_SETMARGINLEFT", "SCI_SETMARGINRIGHT",
    "SCI_GETLINECOUNT", "SCI_TEXTWIDTH", "SCI_GETMARGINWIDTHN", "SCI_STYLEGETBACK",
    "SC_MARGIN_NUMBER", "STYLE_LINENUMBER", "SCI_GETCURRENTPOS", "SCI_COUNTCHARACTERS",
    "SCN_UPDATEUI", "SCI_GETZOOM", "SCI_SETZOOM", "SCI_ZOOMIN", "SCI_ZOOMOUT", "SCN_ZOOM",
    "SCI_GETRANGEPOINTER", "SCI_DOCLINEFROMVISIBLE",
    "SCI_VISIBLEFROMDOCLINE", "SC_UPDATE_V_SCROLL", "SCI_GOTOPOS", "SCI_DOCUMENTEND",
    "SCI_GETANCHOR", "SCI_GETLINE", "SCI_LINELENGTH",
    "SCFIND_REGEXP", "SCFIND_CXX11REGEX", "SCFIND_POSIX", "SCI_GETTARGETEND",
    "SCI_POSITIONAFTER", "SCI_POSITIONBEFORE", "SCI_POSITIONFROMLINE", "SCI_ISRANGEWORD"
)

function Add-Definitions {
    param(
        [Parameter(Mandatory = $true)] [string]$InterfacePath,
        [Parameter(Mandatory = $true)] [hashtable]$Definitions
    )

    foreach ($line in Get-Content -LiteralPath $InterfacePath) {
        if ($line -match '^(fun|get|set|evt)\s+\S+\s+([A-Za-z0-9_]+)=([^\s(]+)') {
            $prefix = if ($Matches[1] -eq "evt") { "SCN_" } else { "SCI_" }
            $Definitions["$prefix$($Matches[2].ToUpperInvariant())"] = $Matches[3]
        }
        elseif ($line -match '^val\s+([A-Z0-9_]+)=([^\s]+)') {
            $Definitions[$Matches[1]] = $Matches[2]
        }
    }
}

$Definitions = @{}
Add-Definitions -InterfacePath $ScintillaInterface -Definitions $Definitions
Add-Definitions -InterfacePath $LexillaInterface -Definitions $Definitions

$MissingNames = @($RequiredNames | Where-Object { -not $Definitions.ContainsKey($_) })
if ($MissingNames.Count -ne 0) {
    throw "Required Scintilla constants were not found: $($MissingNames -join ', ')"
}

$Lines = @(
    "// Generated by tools/generate-scintilla-constants.ps1 from Scintilla 5.6.6 and Lexilla 5.5.3.",
    "// Do not edit by hand.",
    ""
)
foreach ($name in $RequiredNames | Sort-Object) {
    $Lines += "pub const $($name): u32 = $($Definitions[$name]);"
}

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputPath) | Out-Null
[System.IO.File]::WriteAllLines($OutputPath, $Lines, [System.Text.UTF8Encoding]::new($false))
