[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)] [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepositoryRoot = Split-Path -Parent $PSScriptRoot
$Target = "x86_64-pc-windows-msvc"

Push-Location $RepositoryRoot
try {
    $json = & cargo metadata --locked --format-version 1 --filter-platform $Target
    if ($LASTEXITCODE -ne 0) {
        throw "cargo metadata --locked failed."
    }
}
finally {
    Pop-Location
}

$metadata = $json | ConvertFrom-Json
$packagesById = @{}
foreach ($package in $metadata.packages) {
    $packagesById[$package.id] = $package
}
$nodesById = @{}
foreach ($node in $metadata.resolve.nodes) {
    $nodesById[$node.id] = $node
}

function Test-ProcMacro {
    param($Package)
    return [bool]($Package.targets | Where-Object { $_.kind -contains "proc-macro" })
}

function Test-NormalEdge {
    param($Edge)
    return [bool]($Edge.dep_kinds | Where-Object { $null -eq $_.kind })
}

# Linked closure: normal (non-build, non-dev) edges, excluding compile-time procedural macros.
$linked = [System.Collections.Generic.HashSet[string]]::new()
$pending = [System.Collections.Generic.Stack[string]]::new()
foreach ($edge in $nodesById[$metadata.resolve.root].deps) {
    if (Test-NormalEdge $edge) { $pending.Push($edge.pkg) }
}
while ($pending.Count -gt 0) {
    $id = $pending.Pop()
    if ((Test-ProcMacro $packagesById[$id]) -or -not $linked.Add($id)) {
        continue
    }
    foreach ($edge in $nodesById[$id].deps) {
        if (Test-NormalEdge $edge) { $pending.Push($edge.pkg) }
    }
}

$text = [System.Text.StringBuilder]::new()
[void]$text.Append("Rust crates statically linked into FastPad.exe`n")
[void]$text.Append("Generated by tools/rust-crate-licenses.ps1 from cargo metadata --locked and the crate sources.`n")
$packages = @($linked | ForEach-Object { $packagesById[$_] } | Sort-Object name, version)
foreach ($package in $packages) {
    $directory = Split-Path -Parent $package.manifest_path
    $files = @(Get-ChildItem -LiteralPath $directory -File |
        Where-Object { $_.Name -match '^(LICEN[CS]E|COPYING|UNLICENSE|NOTICE)' } |
        Sort-Object Name)
    if ($files.Count -eq 0) {
        throw "No license files found for $($package.name) $($package.version) in '$directory'."
    }
    [void]$text.Append("`n================================================================================`n")
    [void]$text.Append("$($package.name) $($package.version)`nLicense: $($package.license)`n")
    foreach ($file in $files) {
        $body = (Get-Content -Raw -LiteralPath $file.FullName) -replace "`r`n", "`n"
        [void]$text.Append("`n---- $($file.Name) ----`n`n$($body.TrimEnd())`n")
    }
}

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputPath) | Out-Null
[System.IO.File]::WriteAllText($OutputPath, $text.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Output "Wrote license texts for $($packages.Count) linked crates: $(($packages | ForEach-Object { "$($_.name) $($_.version)" }) -join ', ')"
